### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by kephale** [napari/napari-svg#30]
@sofroniewn @tlambert03 

We need to do a release of napari-svg to resolve https://github.com/napari/napari/pull/5582

It seems like the two of you are the maintainers of napari-svg on pypi. Could you give access to someone else on pypi (my handle there is kisharrington)?

Thank you!

**Comment by sofroniewn** [comment]
@kephale just invited you to be a maintainer - let me know if you need more

**Comment by kephale** [comment]
@sofroniewn shucks, I don't have proper access rights to this repo on Github. I need to be able to push to cut a new release. Could you please add me?

**Comment by Czaki** [comment]
I have pushed v0.1.7 to not block work until someone solve permissions
