### ISSUE TITLE
project now depends on napari but not listed in deps

### ISSUE THREAD

**Issue by tlambert03** [napari/napari-svg#32]
#29 added an import-time dependency on napari but didn't add napari to the dependencies...
this is proving problematic for npe2 tests (which were using napari-svg as an example plugin).

npe2 probably shouldn't use this package for testing, but this package should also list its dependencies properly

**Comment by brisvag** [comment]
Ouch, you're right :/ Will add now!

**Comment by jni** [comment]
Closed by #34
